### ISSUE TITLE
Compound subgraph has stopped indexing as of block 15,442,130 (Aug-30-2022 07:15:59 PM +UTC)

### ISSUE THREAD

**Issue by welps** [graphprotocol/compound-v2-subgraph#21]
Hello,

https://thegraph.com/hosted-service/subgraph/graphprotocol/compound-v2 no longer works and is now returning indexing errors.

If this is not the right place to report this kind of issue, please direct me to where I should report. Thanks.

**Comment by exa256** [comment]
seconded, got error message `message: 'indexing_error` from all Compound markets

**Comment by welps** [comment]
Hi @juanmardefago , sorry for pinging you on this, but how can we put this on the graph's radar?

**Comment by juanmardefago** [comment]
Hey @welps! Thanks for the heads-up, I've already let the team know!

Sorry for the inconvenience!

**Comment by LefterisJP** [comment]
+1. I really though this would have been fixed earlier since the issue was made but it seems it persists for a week now.

**Comment by juanmardefago** [comment]
So, looking into this, I think the bug was caused by an upgrade in the Compound Oracle, since [it was upgraded just before the subgraph broke](https://compound.finance/governance/proposals/117)

I'll check what the changes required for this to keep working are, and try to come with a solution pretty soon!

**Comment by juanmardefago** [comment]
@LefterisJP @welps I've deployed a fix, and the team is gonna move the deployment to the usual endpoint soon(Compound V2 subgraph has some extra js wrappers on top, so I unfortunately can't deploy it myself).

Small caveat, since the botched price oracle doesn't allow for some of the calculations to be done, some values might be wonky until a proper price oracle is set on-chain.

BTW, this subgraph isn't being actively worked on (or even maintained, aside from the occasional bug fix I can deploy). I'd recommend migrating to the Messari subgraphs, since they are actively working on standardizing and integrating more and more lending protocols, and have tons of those subgraphs being heavily worked on and maintained. (https://subgraphs.messari.io/)

Also, using standardized subgraphs should most likely be quite a lot easier to integrate rather than having specific subgraph implementations for each protocol.

**Comment by juanmardefago** [comment]
In the meantime, if you absolutely need the subgraph now, the current latest fix is here: https://thegraph.com/hosted-service/subgraph/juanmardefago/compound-v2 (current version is grafted, to make it sync faster, but I also redeployed it without grafting to have it fully sync normally too).

**Comment by juanmardefago** [comment]
@LefterisJP @welps the original endpoint is back online :) (https://thegraph.com/hosted-service/subgraph/graphprotocol/compound-v2)

@welps I can't close the issue myself, since I don't have the permissions, so feel free to close it whenever you can :)

**Comment by welps** [comment]
Thank you for handling this! @juanmardefago
